name: Build and Deploy of Static Site

on:
  push:

permissions:
  contents: write
  pages: write

jobs:
  builddeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: MkDocs Setup
        run: pip install mkdocs

      - name: Build
        run: mkdocs build --clean

      - name: Deploy
        run: mkdocs gh-deploy --force

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: builddeploy

    steps:
      - uses: actions/setup-node@v1

      - name: Check npm version
        run: npm -version

      - name: Install ESLint
        run: npm install eslint

      - name: ls
        run: ls -R