name: Build and Deploy of Static Site

on:
  push:

permissions:
  contents: write
  pages: write

jobs:
  builddeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: MkDocs Setup
        run: pip install mkdocs

      - name: Build
        run: mkdocs build --clean

      - name: Deploy
        run: mkdocs gh-deploy --force

#      - name: Node Setup
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20

#      - name: Install ESLint
#        run: npm install eslint
#
#      - name: cd
#        run: cd /home/runner/work/pythonWebPrj1/pythonWebPrj1/site
#
#      - name: ls
#        run: ls -R
#
#      - name: Run ESLint
#        uses: sibiraj-s/action-eslint@v3
#        with:
#          eslint-args: '--ignore-path=.gitignore --quiet'
#          extensions: 'js,jsx,ts,tsx,html'
#          annotations: true